# Note to self: if edit this, restart server
# Site settings
title: wasita
# subtitle:
description: >- # this means to ignore newlines until "baseurl:"
author: wasita mahaphanit
email: wasita.mahaphanit.gr@dartmouth.edu
avatar: assets/images/avatar/2020_virtual_apda_hike.png

# Customize url and baseurl for site:
# for local testing, leave empty
# baseurl: /home
url: https://wasita.github.io

# Social settings
twitter_url: https://twitter.com/mahaphanit
facebook_url:
googleplus_url:
instagram_url:
linkedin_url:
github_url: https://github.com/wasita
stackoverflow_url:
pinterest_url:
slack_url:
dribbble_url:

# Google Analytics Tracking ID goes here:
google_analytics: 'UA-171673875-1'

# The following settings are NECESSARY for the Prologue theme to run:
# theme: jekyll-theme-prologue
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]

# For CV
style: davewhipp
cv: /assets/pdfs/WasitaCV.pdf
